import { getBaseName } from '@/components/StreamingProviders';

const PROVIDER_URLS: Record<string, string> = {
  'Netflix': 'https://www.netflix.com',
  'Amazon Prime Video': 'https://www.primevideo.com',
  'Prime Video': 'https://www.primevideo.com',
  'Amazon Video': 'https://www.amazon.co.uk/gp/video/storefront',
  'Apple TV': 'https://tv.apple.com',
  'Apple TV Plus': 'https://tv.apple.com',
  'iTunes': 'https://tv.apple.com',
  'Disney Plus': 'https://www.disneyplus.com',
  'Hulu': 'https://www.hulu.com',
  'Max': 'https://play.max.com',
  'HBO Max': 'https://play.max.com',
  'Paramount Plus': 'https://www.paramountplus.com',
  'Peacock': 'https://www.peacocktv.com',
  'BBC iPlayer': 'https://www.bbc.co.uk/iplayer',
  'ITVX': 'https://www.itv.com/watch',
  'Channel 4': 'https://www.channel4.com',
  'Sky Go': 'https://www.skygo.sky.com',
  'Sky Store': 'https://www.skystore.com',
  'NOW': 'https://www.nowtv.com',
  'MUBI': 'https://mubi.com',
  'Curzon Home Cinema': 'https://www.curzon.com/home-cinema',
  'Crunchyroll': 'https://www.crunchyroll.com',
  'Shudder': 'https://www.shudder.com',
  'BritBox': 'https://www.britbox.com',
  'Lionsgate Plus': 'https://www.lionsgateplus.com',
  'StudioCanal Presents': 'https://www.studiocanal.com',
  'Plex': 'https://watch.plex.tv',
  'Tubi': 'https://tubitv.com',
  'Pluto TV': 'https://pluto.tv',
  'Freevee': 'https://www.amazon.co.uk/gp/video/storefront',
  'Amazon Freevee': 'https://www.amazon.co.uk/gp/video/storefront',
  'Google Play Movies': 'https://play.google.com/store/movies',
  'YouTube': 'https://www.youtube.com/movies',
  'YouTube Premium': 'https://www.youtube.com/premium',
  'Microsoft Store': 'https://www.microsoft.com/en-gb/store/movies-and-tv',
  'Xbox': 'https://www.microsoft.com/en-gb/store/movies-and-tv',
  'Rakuten TV': 'https://rakuten.tv',
  'Chili': 'https://uk.chili.com',
  'Vudu': 'https://www.fandangoathome.com',
  'Fandango At Home': 'https://www.fandangoathome.com',
  'Redbox': 'https://www.redbox.com',
  'Starz': 'https://www.starz.com',
  'Showtime': 'https://www.sho.com',
  'AMC Plus': 'https://www.amcplus.com',
  'Discovery Plus': 'https://www.discoveryplus.com',
  'ESPN Plus': 'https://plus.espn.com',
  'Paramount Plus Showtime': 'https://www.paramountplus.com',
  'Funimation': 'https://www.crunchyroll.com',
  'Acorn TV': 'https://acorn.tv',
  'Hoopla': 'https://www.hoopladigital.com',
  'Kanopy': 'https://www.kanopy.com',
  'Rakuten Viki': 'https://www.viki.com',
  'Sundance Now': 'https://www.sundancenow.com',
  'Arrow': 'https://www.arrow-player.com',
  'Arrow Player': 'https://www.arrow-player.com',
  'Filmzie': 'https://www.filmzie.com',
  'Guidedoc': 'https://www.guidedoc.tv',
  'Hoichoi': 'https://www.hoichoi.tv',
  'Eros Now': 'https://erosnow.com',
  'Zee5': 'https://www.zee5.com',
  'JioCinema': 'https://www.jiocinema.com',
  'Spamflix': 'https://www.spamflix.com',
  'MagellanTV': 'https://www.magellantv.com',
  'DocAlliance Films': 'https://dafilms.com',
  'Broadway HD': 'https://www.broadwayhd.com',
  'OVID': 'https://ovid.tv',
  'Film Movement Plus': 'https://filmmovementplus.com',
  'IndieFlix': 'https://www.indieflix.com',
  'Flix Premiere': 'https://flixpremiere.com',
  'The Criterion Channel': 'https://www.criterionchannel.com',
  'Criterion Channel': 'https://www.criterionchannel.com',
  'BFI Player': 'https://player.bfi.org.uk',
};

export function getProviderUrl(name: string): string {
  const base = getBaseName(name);
  const mapped = PROVIDER_URLS[base];
  if (mapped) return mapped;
  return `https://www.google.com/search?q=${encodeURIComponent(`${base} watch movies stream`)}`;
}
